BORDER_WIDTH = 1

WINDOW_DEFAULT_STRIPE_HEIGHT = 20
WINDOW_DEFAULT_BORDER_RADIUS = 10

LOWER_UI_BAR_HEIGHT = 40

XP_BAR_HEIGHT = 5
XP_BAR_PARTS = 8

MINI_BARS_X = 50
MINI_BARS_WIDTH = 100
MINI_BARS_HEIGHT = 8
MINI_BARS_PARTS = 4

OPEN_MENU_BUTTON_OFFSET_X = 40
MENU_BUTTON_WIDTH = 200
MENU_BUTTON_HEIGHT = 50

INTERFACE_TILE_SIZE = 50
