import pygame

KEY_SWITCH_SHOW_INTERFACE = pygame.K_F1
KEY_SWITCH_SHOW_FPS_RATE = pygame.K_F2

KEY_SWITCH_SHOW_FRIENDLY_NPC_MINI_HP_BARS = pygame.K_z
KEY_SWITCH_SHOW_HOSTILE_NPC_MINI_HP_BARS = pygame.K_v
KEY_SWITCH_SHOW_LOOT_NAMES = pygame.K_t

KEY_SWITCH_OPEN_INVENTORY = pygame.K_b
KEY_SWITCH_OPEN_EQUIPMENT = pygame.K_c

KEY_SWITCH_OPEN_CHAT = pygame.K_r
KEY_SWITCH_OPEN_CHAT_INPUT_BOX = pygame.K_RETURN

KEY_USE_HP_POTION = pygame.K_q
KEY_USE_MANA_POTION = pygame.K_e
